### ISSUE TITLE
$(L_DIR)/share/pixmaps/ might not exist

### ISSUE THREAD

**Issue by vknecht** [wildtruc/zenvidia#1]
Hello,

on a fresh Fedora 25 install, /usr/local/share/pixmaps/
directory doesn't exist, so the "make install" step fails.

**Comment by wildtruc** [comment]
Oh, Ok. Probably missing the fact that /usr/local/share/pixmaps doesn't exist in /usr/local/share.
Should be probably the same with /usr/share/applications.
Fixed it right now (Makefile -> update 28)

**Comment by wildtruc** [comment]
There  was a few other issues I discover during the fix I did there.
Tell I there is something else.
